import React, { useState } from "react";
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import CustomNavbar from "./components/Navbar";
import CategoryNavbar from "./components/CategoryNavbar";
import "bootstrap/dist/css/bootstrap.min.css";
import BannerCarousel from "./components/BannerCarousel";
import HomePage from "./pages/homePage/homePage";
import Footer from "./composites/footer/Footer";
import PaintingPage from "./composites/paintingpage/PaintingPage";
import SketchesPage from "./composites/sketchespage/SketchesPage";
import SketchbookPage from "./composites/sketchespage/SketchbookPage";
import GraphitePencilPage from "./composites/sketchespage/GraphitePencilPage";
import BrushesPage from "./composites/sketchespage/BrushesPage";
import WatercolorPage from "./composites/sketchespage/WatercolorPage";
import CharcoalsPage from "./composites/sketchespage/Charcoals";
// import ProductList from "./composites/productList/ProductList";
import ProductDetails from "./composites/productList/ProductDetails";
import SellProduct from "./composites/productList/SellProduct";
import Cart from "./composites/cart/Cart";
import SearchResults from "./composites/search/SearchResults";
function App() {
  const [cartItems, setCartItems] = useState([]);
  const [totalPrice, setTotalPrice] = useState(0);
  const [itemCount, setItemCount] = useState(0);
  const MAX_ITEMS = 10;
  const [products] = useState([
    {
      id: 1,
      name: "Abstract Art Painting",
      price: 1199,
      originalPrice: 2999,
      location: "Mumbai",
      description: "Premium Golden Framed Wall paintings for home & office.",
      image: "../images/painting1.jpg",
      size: "89 cm x 51 cm",
      dimensions: "89L x 51W cm",
      items: 3,
      orientation: "Portrait",
      shape: "Rectangular",
      theme: "Madhubani",
      uses: "Living room, Bedroom, Office, Hotel, Dining room, Bathroom, Bar",
      frameType: "Framed",
      wallArtForm: "Painting",
      material: "Cardboard",
      about: [
        "Premium Sparkle lamination for a luxurious look.",
        "High-gloss mirror effect for stunning wall decor.",
        "Perfect for living rooms, bedrooms, and offices.",
        "Safely packaged in a rigid hard-board box.",
        "Water-resistant surface ensures long-lasting decor.",]
    },
    {
      id: 2,
      name: "Watercolor Landscape Art",
      price: 1299,
      originalPrice: 3099,
      location: "Delhi",
      description: "Create art for imaginary realms.",
      image: "../images/brushes3.jpg",
      size: "90 cm x 52 cm",
      dimensions: "90L x 52W cm",
      items: 2,
      orientation: "Landscape",
      shape: "Square",
      theme: "Nature",
      uses: "Living room, Garden, Studio",
      frameType: "Unframed",
      wallArtForm: "Watercolor",
      material: "Paper",
      about: [
        "Vivid watercolor hues for a natural feel.",
        "Eco-friendly materials for sustainable decor.",
        "Ideal for outdoor and indoor spaces.",
        "Packaged with care in recyclable tubes.",
        "Fade-resistant for lasting beauty."
      ]
    },
    {
      id: 3,
      "name": "Sketched Portrait Canvas",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Kolkata",
      "description": "Design posters or programs for theaters.",
      "image": "../images/sketchbook1.jpg",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Portraits",
      "uses": "Theater, Gallery, Home",
      "frameType": "Framed",
      "wallArtForm": "Sketch",
      "material": "Canvas",
      "about": [
        "Hand-drawn details for a personal touch.",
        "Archival quality for long-term preservation.",
        "Perfect for theater lobbies and homes.",
        "Shipped in protective wooden crates.",
        "Customizable to suit your style."
      ]
    },
    {
      id: 4,
      "name": "Golden Abstract Wall Art",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Chennai",
      "description": "Use art to explain machinery or software.",
      "image": "../images/painting2.jpg",
      "size": "92 cm x 54 cm",
      "dimensions": "92L x 54W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Abstract",
      "uses": "Office, Workshop, Study",
      "frameType": "Framed",
      "wallArtForm": "Painting",
      "material": "Wood",
      "about": [
        "Metallic gold finish for a modern look.",
        "Durable wood frame for stability.",
        "Great for technical office spaces.",
        "Packaged with reinforced corners.",
        "Resistant to scratches and wear."
      ]
    },
    {
      id: 5,
      "name": "Watercolor Floral Design",
      "price": 1199,
      "originalPrice": 2999,
      "location": "Bangalore",
      "description": "Create custom art for weddings.",
      "image": "../images/painting3.jpg",
      "size": "88 cm x 50 cm",
      "dimensions": "88L x 50W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Circular",
      "theme": "Floral",
      "uses": "Wedding Hall, Home, Event Space",
      "frameType": "Unframed",
      "wallArtForm": "Watercolor",
      "material": "Paper",
      "about": [
        "Delicate floral patterns for elegance.",
        "Lightweight for easy hanging.",
        "Ideal for wedding decorations.",
        "Packaged in elegant gift boxes.",
        "Waterproof coating for durability."
      ]
    },
    {
      id: 6,
      "name": "Charcoal Cityscape Sketch",
      "price": 999,
      "originalPrice": 2499,
      "location": "Hyderabad",
      "description": "Design menus or wall art for restaurants.",
      "image": "../images/sketch1.jpg",
      "size": "87 cm x 49 cm",
      "dimensions": "87L x 49W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Urban",
      "uses": "Restaurant, Cafe, Kitchen",
      "frameType": "Framed",
      "wallArtForm": "Charcoal",
      "material": "Paper",
      "about": [
        "Bold charcoal lines for a dramatic effect.",
        "Acid-free paper for longevity.",
        "Perfect for dining area decor.",
        "Shipped with protective sleeves.",
        "Easy to clean surface."
      ]
    },
    {
      id: 7,
      "name": "Modern Abstract Canvas",
      "price": 1499,
      "originalPrice": 3499,
      "location": "Pune",
      "description": "Use art in journalism or reporting.",
      "image": "../images/painting4.jpg",
      "size": "91 cm x 53 cm",
      "dimensions": "91L x 53W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Square",
      "theme": "Modern",
      "uses": "Newsroom, Office, Library",
      "frameType": "Unframed",
      "wallArtForm": "Painting",
      "material": "Canvas",
      "about": [
        "Bold colors for a contemporary vibe.",
        "Canvas material for a textured look.",
        "Great for newsroom inspiration.",
        "Packaged in sturdy cardboard tubes.",
        "UV-resistant for color preservation."
      ]
    },
    {
      id: 8,
      "name": "Watercolor Nature Scene",
      "price": 1299,
      "originalPrice": 3099,
      "location": "Jaipur",
      "description": "Use art to highlight handmade products.",
      "image": "../images/watercolor1.jpg",
      "size": "89 cm x 51 cm",
      "dimensions": "89L x 51W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Nature",
      "uses": "Craft Shop, Home, Gallery",
      "frameType": "Framed",
      "wallArtForm": "Watercolor",
      "material": "Paper",
      "about": [
        "Soft watercolor tones for a natural feel.",
        "Handmade paper for authenticity.",
        "Ideal for showcasing crafts.",
        "Packaged with eco-friendly wraps.",
        "Moisture-resistant for longevity."
      ]
    },
    {
      id: 9,
      "name": "Graphite Wildlife Drawing",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Ahmedabad",
      "description": "Design room decor or lobby art.",
      "image": "../images/Grapencil1.jpg",
      "size": "86 cm x 48 cm",
      "dimensions": "86L x 48W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Wildlife",
      "uses": "Hotel Lobby, Home, Office",
      "frameType": "Framed",
      "wallArtForm": "Graphite",
      "material": "Paper",
      "about": [
        "Detailed graphite shading for realism.",
        "High-quality paper for fine lines.",
        "Perfect for lobby enhancements.",
        "Shipped in protective portfolios.",
        "Smudge-proof coating applied."
      ]
    },
    {
      id: 10,
      "name": "Abstract Oil Painting",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Surat",
      "description": "Use art to complement exhibits.",
      "image": "../images/painting5.jpg",
      "size": "90 cm x 52 cm",
      "dimensions": "90L x 52W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Abstract",
      "uses": "Museum, Gallery, Home",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Rich oil colors for depth.",
        "Canvas stretched for durability.",
        "Enhances museum exhibits.",
        "Packaged in reinforced crates.",
        "Oil-resistant finish for protection."
      ]
    },
    {
      id: 11,
      "name": "Watercolor Cityscape",
      "price": 1299,
      "originalPrice": 3099,
      "location": "Nagpur",
      "description": "Use art to depict destinations.",
      "image": "../images/watercolor2.jpg",
      "size": "87 cm x 49 cm",
      "dimensions": "87L x 49W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Cityscape",
      "uses": "Travel Agency, Home, Office",
      "frameType": "Framed",
      "wallArtForm": "Watercolor",
      "material": "Paper",
      "about": [
        "Vivid city scenes in watercolor.",
        "Acid-free paper for preservation.",
        "Perfect for travel decor.",
        "Shipped in protective sleeves.",
        "Waterproof for durability."
      ]
    },
    {
      id: 12,
      "name": "Watercolor Wildlife Art",
      "price": 1299,
      "originalPrice": 3099,
      "location": "Kanpur",
      "description": "Design banners or backdrops for conferences.",
      "image": "../images/watercolor3.jpg",
      "size": "89 cm x 51 cm",
      "dimensions": "89L x 51W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Circular",
      "theme": "Wildlife",
      "uses": "Conference Hall, Office, Home",
      "frameType": "Framed",
      "wallArtForm": "Watercolor",
      "material": "Paper",
      "about": [
        "Bright wildlife watercolor hues.",
        "High-quality paper for vibrancy.",
        "Ideal for conference decor.",
        "Shipped in reinforced tubes.",
        "Water-resistant for longevity."
      ]
    },
    {
      id: 13,
      "name": "Oil Portrait Painting",
      "price": 1499,
      "originalPrice": 3499,
      "location": "Bhopal",
      "description": "Showcase regional art in galleries or events.",
      "image": "../images/painting6.jpg",
      "size": "91 cm x 53 cm",
      "dimensions": "91L x 53W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Square",
      "theme": "Portraits",
      "uses": "Gallery, Event Space, Home",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Rich oil portrait details.",
        "Canvas for a classic look.",
        "Perfect for gallery displays.",
        "Shipped in wooden crates.",
        "UV-protected for longevity."
      ]
    },
    {
      id: 14,
      "name": "Oil Landscape Painting",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Coimbatore",
      "description": "Create backdrops for theater productions.",
      "image": "../images/painting7.jpg",
      "size": "90 cm x 52 cm",
      "dimensions": "90L x 52W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Square",
      "theme": "Landscape",
      "uses": "Theater, Studio, Home",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Vivid oil landscape colors.",
        "Sturdy canvas for durability.",
        "Great for theater sets.",
        "Shipped in protective crates.",
        "Oil-resistant for preservation."
      ]
    },
    {
      id: 15,
      "name": "Oil Cityscape Art",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Agra",
      "description": "Use art in contracts or legal papers.",
      "image": "../images/painting8.jpg",
      "size": "91 cm x 53 cm",
      "dimensions": "91L x 53W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Cityscape",
      "uses": "Law Office, Home, Office",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Rich oil city scenes.",
        "Canvas for a professional look.",
        "Ideal for legal decor.",
        "Shipped in wooden crates.",
        "UV-protected for longevity."
      ]
    },
    {
      id: 16,
      "name": "Oil Nature Painting",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Jodhpur",
      "description": "Use art to share traditions and stories.",
      "image": "../images/painting9.jpg",
      "size": "90 cm x 52 cm",
      "dimensions": "90L x 52W cm",
      "items": 2,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Nature",
      "uses": "Cultural Center, Home, Gallery",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Vivid oil nature scenes.",
        "Canvas for a rich texture.",
        "Perfect for cultural decor.",
        "Shipped in wooden crates.",
        "UV-protected for longevity."
      ]
    },
    {
      id: 17,
      "name": "Oil Abstract Painting",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Aurangabad",
      "description": "Create artistic invitations for weddings or parties.",
      "image": "../images/painting10.jpg",
      "size": "91 cm x 53 cm",
      "dimensions": "91L x 53W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Abstract",
      "uses": "Wedding Hall, Home, Event Space",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Elegant oil abstract designs.",
        "Canvas for a rich texture.",
        "Perfect for wedding invites.",
        "Shipped in wooden crates.",
        "UV-protected for longevity."
      ]
    },
    {
      id: 18,
      "name": "Oil Wildlife Painting",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Dehradun",
      "description": "Develop sculptures or installations for public spaces.",
      "image": "../images/painting11.jpg",
      "size": "90 cm x 52 cm",
      "dimensions": "90L x 52W cm",
      "items": 2,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Wildlife",
      "uses": "Park, Public Space, Home",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Vivid oil wildlife depictions.",
        "Canvas for a bold look.",
        "Ideal for public installations.",
        "Shipped in wooden crates.",
        "UV-protected for longevity."
      ]
    },
    {
      id: 19,
      "name": "Oil Portrait Art",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Trivandrum",
      "description": "Use art in store displays or window dressing.",
      "image": "../images/painting12.jpg",
      "size": "91 cm x 53 cm",
      "dimensions": "91L x 53W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Portraits",
      "uses": "Retail Store, Home, Shop",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Elegant oil portrait designs.",
        "Canvas for a rich texture.",
        "Perfect for store displays.",
        "Shipped in wooden crates.",
        "UV-protected for longevity."
      ]
    },
    {
      id: 20,
      "name": "Oil Abstract Form",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Shimla",
      "description": "Create art that captures athletic events or achievements.",
      "image": "../images/painting13.jpg",
      "size": "90 cm x 52 cm",
      "dimensions": "90L x 52W cm",
      "items": 2,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Abstract",
      "uses": "Gym, Sports Club, Home",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Dynamic oil athletic art.",
        "Canvas for a bold look.",
        "Ideal for sports decor.",
        "Shipped in wooden crates.",
        "UV-protected for longevity."
      ]
    },
    {
      id: 21,
      "name": "Oil Cityscape Painting",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Trivandrum",
      "description": "Use art to visualize scientific concepts or data.",
      "image": "../images/painting14.jpg",
      "size": "91 cm x 53 cm",
      "dimensions": "91L x 53W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Cityscape",
      "uses": "Science Lab, Home, Office",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Scientific oil city scenes.",
        "Canvas for a rich texture.",
        "Ideal for lab decor.",
        "Shipped in wooden crates.",
        "UV-protected for longevity."
      ]
    },
    {
      id: 22,
      "name": "Oil Nature Scene",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Dehradun",
      "description": "Organize art projects that involve community participation.",
      "image": "../images/painting15.jpg",
      "size": "90 cm x 52 cm",
      "dimensions": "90L x 52W cm",
      "items": 2,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Nature",
      "uses": "Community Center, Home, Park",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Community oil nature art.",
        "Canvas for a rich texture.",
        "Ideal for public projects.",
        "Shipped in wooden crates.",
        "UV-protected for longevity."
      ]
    },
    {
      id: 23,
      "name": "Oil Cityscape Scene",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Trivandrum",
      "description": "Use art in spas, yoga studios, or meditation rooms.",
      "image": "../images/painting16.jpg",
      "size": "91 cm x 53 cm",
      "dimensions": "91L x 53W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Cityscape",
      "uses": "Spa, Yoga Studio, Home",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Calming oil city scenes.",
        "Canvas for a serene look.",
        "Ideal for spa decor.",
        "Shipped in wooden crates.",
        "UV-protected for longevity."
      ]
    },
    {
      id: 24,
      "name": "Oil Portrait Painting",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Dehradun",
      "description": "Create patterns or prints for clothing and accessories.",
      "image": "../images/painting17.jpg",
      "size": "91 cm x 53 cm",
      "dimensions": "91L x 53W cm",
      "items": 2,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Portraits",
      "uses": "Fashion Studio, Home, Boutique",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Fashionable oil portrait prints.",
        "Canvas for a rich texture.",
        "Ideal for clothing design.",
        "Shipped in wooden crates.",
        "UV-protected for longevity."
      ]
    },
    {
      id: 25,
      "name": "Oil Abstract Scene",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Trivandrum",
      "description": "Design art pieces as mementos for tourists or events.",
      "image": "../images/painting18.jpg",
      "size": "91 cm x 53 cm",
      "dimensions": "91L x 53W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Abstract",
      "uses": "Tourist Shop, Event Space, Home",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Memento oil abstract art.",
        "Canvas for a rich texture.",
        "Ideal for tourist gifts.",
        "Shipped in wooden crates.",
        "UV-protected for longevity."
      ]
    },
    {
      id: 26,
      "name": "Sketched Abstract Design",
      "price": 1199,
      "originalPrice": 2999,
      "location": "Lucknow",
      "description": "Create artistic packaging for goods.",
      "image": "../images/sketch2.jpg",
      "size": "88 cm x 50 cm",
      "dimensions": "88L x 50W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Circular",
      "theme": "Abstract",
      "uses": "Retail, Home, Gift Shop",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Minimalist sketch for modern packaging.",
        "Lightweight paper for versatility.",
        "Great for product branding.",
        "Packaged in recyclable boxes.",
        "Fade-resistant for long use."
      ]
    },
    {
      id: 27,
      "name": "Sketched Nature Drawing",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Madurai",
      "description": "Use art in gyms or fitness centers.",
      "image": "../images/sketch3.png",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Nature",
      "uses": "Gym, Home, Studio",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Dynamic sketch for motivation.",
        "Light paper for easy mounting.",
        "Ideal for gym decor.",
        "Packaged in sturdy tubes.",
        "Fade-resistant for use."
      ]
    },
    {
      id: 28,
      "name": "Sketched Wildlife Art",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Varanasi",
      "description": "Design pet portraits or themed art.",
      "image": "../images/sketch4.jpg",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Wildlife",
      "uses": "Pet Shop, Home, Studio",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Detailed wildlife sketches.",
        "Light paper for versatility.",
        "Perfect for pet lovers.",
        "Packaged in protective covers.",
        "Fade-resistant for display."
      ]
    },
    {
      id: 29,
      "name": "Sketched Cityscape",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Udaipur",
      "description": "Design playful and educational art for kids.",
      "image": "../images/sketch5.jpg",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Cityscape",
      "uses": "Playroom, School, Home",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Fun sketches for kids.",
        "Educational paper quality.",
        "Ideal for classroom use.",
        "Packaged in sturdy tubes.",
        "Fade-resistant for kids."
      ]
    },
    {
      id: 30,
      "name": "Sketched Portrait Art",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Jabalpur",
      "description": "Paint or draw likenesses of individuals.",
      "image": "../images/sketch6.jpg",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Portraits",
      "uses": "Home, Studio, Gallery",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Personalized sketch portraits.",
        "High-quality paper for detail.",
        "Ideal for home decor.",
        "Packaged in protective covers.",
        "Fade-resistant for display."
      ]
    },
    {
      id: 31,
      "name": "Sketched Abstract Form",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Ranchi",
      "description": "Use art to bring stories to life for young readers.",
      "image": "../images/sketch7.jpg",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Abstract",
      "uses": "Nursery, Classroom, Home",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Storytelling sketch designs.",
        "Light paper for kids.",
        "Great for young readers.",
        "Packaged in sturdy tubes.",
        "Fade-resistant for use."
      ]
    },
    {
      id: 32,
      "name": "Sketched Wildlife Scene",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Mysore",
      "description": "Design art for various occasions or sentiments.",
      "image": "../images/sketch8.jpg",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Wildlife",
      "uses": "Event Space, Home, Office",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Sentimental wildlife sketches.",
        "Light paper for versatility.",
        "Great for occasion decor.",
        "Packaged in protective covers.",
        "Fade-resistant for display."
      ]
    },
    {
      id: 33,
      "name": "Sketched Portrait Drawing",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Ranchi",
      "description": "Use art in hospitals or clinics to create a calming environment.",
      "image": "../images/sketch9.png",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Portraits",
      "uses": "Hospital, Clinic, Home",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Calming portrait sketches.",
        "Light paper for ease.",
        "Great for hospital decor.",
        "Packaged in protective covers.",
        "Fade-resistant for use."
      ]
    },
    {
      id: 34,
      "name": "Sketched Nature Form",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Mysore",
      "description": "Design art for products like t-shirts, mugs, or posters.",
      "image": "../images/sketch10.jpg",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Nature",
      "uses": "Retail, Home, Gift Shop",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Product-ready nature sketches.",
        "Light paper for printing.",
        "Great for merchandise.",
        "Packaged in protective covers.",
        "Fade-resistant for use."
      ]
    },
    {
      id: 35,
      "name": "Sketched City Design",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Ranchi",
      "description": "Use art to educate about different periods and styles.",
      "image": "../images/sketch11.jpg",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Cityscape",
      "uses": "School, Library, Home",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Educational city sketches.",
        "Light paper for ease.",
        "Great for art history.",
        "Packaged in sturdy tubes.",
        "Fade-resistant for use."
      ]
    },
    {
      id: 35,
      "name": "Sketched Nature Sketch",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Mysore",
      "description": "Use abstract art to represent ideas or emotions.",
      "image": "../images/sketch12.jpg",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Nature",
      "uses": "Studio, Home, Gallery",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Emotional nature sketches.",
        "Light paper for ease.",
        "Great for abstract decor.",
        "Packaged in protective covers.",
        "Fade-resistant for use."
      ]
    },
    {
      id: 37,
      "name": "Sketched Cityscape Art",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Ranchi",
      "description": "Make art that serves a purpose, like decorative furniture.",
      "image": "../images/sketch13.jpg",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Cityscape",
      "uses": "Furniture Store, Home, Office",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Wood",
      "about": [
        "Functional cityscape sketches.",
        "Wood for furniture art.",
        "Great for decor pieces.",
        "Packaged in protective covers.",
        "Fade-resistant for use."
      ]
    },
    {
      id: 38,
      "name": "Sketched Portrait Form",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Mysore",
      "description": "Develop logos, packaging, or branding materials for companies.",
      "image": "../images/sketch14.jpg",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Portraits",
      "uses": "Corporate Office, Home, Shop",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Branding portrait sketches.",
        "Light paper for printing.",
        "Great for company logos.",
        "Packaged in protective covers.",
        "Fade-resistant for use."
      ]
    },
    {
      id: 39,
      name: "Abstract Art Painting",
      price: 1199,
      originalPrice: 2999,
      location: "Mumbai",
      description: "Use art to share traditions and stories.",
      image: "../images/sketchbook1.jpg",
      size: "89 cm x 51 cm",
      dimensions: "89L x 51W cm",
      items: 3,
      orientation: "Portrait",
      shape: "Rectangular",
      theme: "Madhubani",
      uses: "Living room, Bedroom, Office, Hotel, Dining room, Bathroom, Bar",
      frameType: "Framed",
      wallArtForm: "Painting",
      material: "Cardboard",
      about: [
        "Premium Sparkle lamination for a luxurious look.",
        "High-gloss mirror effect for stunning wall decor.",
        "Perfect for living rooms, bedrooms, and offices.",
        "Safely packaged in a rigid hard-board box.",
        "Water-resistant surface ensures long-lasting decor.",]
    },
    {
      id: 40,
      name: "Abstract Art Painting",
      price: 1199,
      originalPrice: 2999,
      location: "Mumbai",
      description: "Design playful and educational art for kids.",
      image: "../images/sketchbook2.jpg",
      size: "89 cm x 51 cm",
      dimensions: "89L x 51W cm",
      items: 3,
      orientation: "Portrait",
      shape: "Rectangular",
      theme: "Madhubani",
      uses: "Living room, Bedroom, Office, Hotel, Dining room, Bathroom, Bar",
      frameType: "Framed",
      wallArtForm: "Painting",
      material: "Cardboard",
      about: [
        "Premium Sparkle lamination for a luxurious look.",
        "High-gloss mirror effect for stunning wall decor.",
        "Perfect for living rooms, bedrooms, and offices.",
        "Safely packaged in a rigid hard-board box.",
        "Water-resistant surface ensures long-lasting decor.",]
    },
    {
      id: 41,
      name: "Abstract Art Painting",
      price: 1199,
      originalPrice: 2999,
      location: "Mumbai",
      description: "Use art to inspire creativity in offices.",
      image: "../images/sketchbook3.jpg",
      size: "89 cm x 51 cm",
      dimensions: "89L x 51W cm",
      items: 3,
      orientation: "Portrait",
      shape: "Rectangular",
      theme: "Madhubani",
      uses: "Living room, Bedroom, Office, Hotel, Dining room, Bathroom, Bar",
      frameType: "Framed",
      wallArtForm: "Painting",
      material: "Cardboard",
      about: [
        "Premium Sparkle lamination for a luxurious look.",
        "High-gloss mirror effect for stunning wall decor.",
        "Perfect for living rooms, bedrooms, and offices.",
        "Safely packaged in a rigid hard-board box.",
        "Water-resistant surface ensures long-lasting decor.",]
    },
    {
      id: 42,
      name: "Abstract Art Painting",
      price: 1199,
      originalPrice: 2999,
      location: "Mumbai",
      description: "Use art to make recipes visually appealing.",
      image: "../images/sketchbook4.jpg",
      size: "89 cm x 51 cm",
      dimensions: "89L x 51W cm",
      items: 3,
      orientation: "Portrait",
      shape: "Rectangular",
      theme: "Madhubani",
      uses: "Living room, Bedroom, Office, Hotel, Dining room, Bathroom, Bar",
      frameType: "Framed",
      wallArtForm: "Painting",
      material: "Cardboard",
      about: [
        "Premium Sparkle lamination for a luxurious look.",
        "High-gloss mirror effect for stunning wall decor.",
        "Perfect for living rooms, bedrooms, and offices.",
        "Safely packaged in a rigid hard-board box.",
        "Water-resistant surface ensures long-lasting decor.",]
    },
    {
      id: 43,
      name: "Abstract Art Painting",
      price: 1199,
      originalPrice: 2999,
      location: "Mumbai",
      description: "Create artistic invitations for weddings or parties.",
      image: "../images/sketchbook5.jpg",
      size: "89 cm x 51 cm",
      dimensions: "89L x 51W cm",
      items: 3,
      orientation: "Portrait",
      shape: "Rectangular",
      theme: "Madhubani",
      uses: "Living room, Bedroom, Office, Hotel, Dining room, Bathroom, Bar",
      frameType: "Framed",
      wallArtForm: "Painting",
      material: "Cardboard",
      about: [
        "Premium Sparkle lamination for a luxurious look.",
        "High-gloss mirror effect for stunning wall decor.",
        "Perfect for living rooms, bedrooms, and offices.",
        "Safely packaged in a rigid hard-board box.",
        "Water-resistant surface ensures long-lasting decor.",]
    },
    {
      id: 44,
      name: "Abstract Art Painting",
      price: 1199,
      originalPrice: 2999,
      location: "Mumbai",
      description: "Paint or draw likenesses of individuals.",
      image: "../images/sketchbook6.jpg",
      size: "89 cm x 51 cm",
      dimensions: "89L x 51W cm",
      items: 3,
      orientation: "Portrait",
      shape: "Rectangular",
      theme: "Madhubani",
      uses: "Living room, Bedroom, Office, Hotel, Dining room, Bathroom, Bar",
      frameType: "Framed",
      wallArtForm: "Painting",
      material: "Cardboard",
      about: [
        "Premium Sparkle lamination for a luxurious look.",
        "High-gloss mirror effect for stunning wall decor.",
        "Perfect for living rooms, bedrooms, and offices.",
        "Safely packaged in a rigid hard-board box.",
        "Water-resistant surface ensures long-lasting decor.",]
    },
    {
      id: 45,
      name: "Abstract Art Painting",
      price: 1199,
      originalPrice: 2999,
      location: "Mumbai",
      description: "Use art in literacy campaigns or book covers.",
      image: "../images/sketchbook7.jpg",
      size: "89 cm x 51 cm",
      dimensions: "89L x 51W cm",
      items: 3,
      orientation: "Portrait",
      shape: "Rectangular",
      theme: "Madhubani",
      uses: "Living room, Bedroom, Office, Hotel, Dining room, Bathroom, Bar",
      frameType: "Framed",
      wallArtForm: "Painting",
      material: "Cardboard",
      about: [
        "Premium Sparkle lamination for a luxurious look.",
        "High-gloss mirror effect for stunning wall decor.",
        "Perfect for living rooms, bedrooms, and offices.",
        "Safely packaged in a rigid hard-board box.",
        "Water-resistant surface ensures long-lasting decor.",]
    },
    {
      id: 46,
      name: "Abstract Art Painting",
      price: 1199,
      originalPrice: 2999,
      location: "Mumbai",
      description: "Design art for churches, temples, or mosques.",
      image: "../images/sketchbook8.jpg",
      size: "89 cm x 51 cm",
      dimensions: "89L x 51W cm",
      items: 3,
      orientation: "Portrait",
      shape: "Rectangular",
      theme: "Madhubani",
      uses: "Living room, Bedroom, Office, Hotel, Dining room, Bathroom, Bar",
      frameType: "Framed",
      wallArtForm: "Painting",
      material: "Cardboard",
      about: [
        "Premium Sparkle lamination for a luxurious look.",
        "High-gloss mirror effect for stunning wall decor.",
        "Perfect for living rooms, bedrooms, and offices.",
        "Safely packaged in a rigid hard-board box.",
        "Water-resistant surface ensures long-lasting decor.",]
    },
    {
      id: 47,
      name: "Abstract Art Painting",
      price: 1199,
      originalPrice: 2999,
      location: "Mumbai",
      description: "Develop sculptures or installations for public spaces.",
      image: "../images/sketchbook9.jpg",
      size: "89 cm x 51 cm",
      dimensions: "89L x 51W cm",
      items: 3,
      orientation: "Portrait",
      shape: "Rectangular",
      theme: "Madhubani",
      uses: "Living room, Bedroom, Office, Hotel, Dining room, Bathroom, Bar",
      frameType: "Framed",
      wallArtForm: "Painting",
      material: "Cardboard",
      about: [
        "Premium Sparkle lamination for a luxurious look.",
        "High-gloss mirror effect for stunning wall decor.",
        "Perfect for living rooms, bedrooms, and offices.",
        "Safely packaged in a rigid hard-board box.",
        "Water-resistant surface ensures long-lasting decor.",]
    },
    {
      id: 48,
      "name": "Graphite Wildlife Drawing",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Ahmedabad",
      "description": "Design room decor or lobby art.",
      "image": "../images/Grapencil1.jpg",
      "size": "86 cm x 48 cm",
      "dimensions": "86L x 48W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Wildlife",
      "uses": "Hotel Lobby, Home, Office",
      "frameType": "Framed",
      "wallArtForm": "Graphite",
      "material": "Paper",
      "about": [
        "Detailed graphite shading for realism.",
        "High-quality paper for fine lines.",
        "Perfect for lobby enhancements.",
        "Shipped in protective portfolios.",
        "Smudge-proof coating applied."
      ]
    },
    {
      id: 49,
      "name": "Graphite Abstract Art",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Patna",
      "description": "Use art to decorate library spaces.",
      "image": "../images/Grapencil2.jpg",
      "size": "86 cm x 48 cm",
      "dimensions": "86L x 48W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Abstract",
      "uses": "Library, Study, Home",
      "frameType": "Unframed",
      "wallArtForm": "Graphite",
      "material": "Paper",
      "about": [
        "Fine graphite lines for detail.",
        "Lightweight paper for ease.",
        "Great for library ambiance.",
        "Packaged in protective covers.",
        "Fade-resistant for durability."
      ]
    },
    {
      id: 50,
      "name": "Graphite Portrait Sketch",
      "price": 999,
      "originalPrice": 2499,
      "location": "Vadodara",
      "description": "Design art for learning toys or games.",
      "image": "../images/Grapencil3.jpg",
      "size": "86 cm x 48 cm",
      "dimensions": "86L x 48W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Circular",
      "theme": "Portraits",
      "uses": "Playroom, Classroom, Home",
      "frameType": "Framed",
      "wallArtForm": "Graphite",
      "material": "Paper",
      "about": [
        "Fine graphite for detail.",
        "Educational paper quality.",
        "Great for toy designs.",
        "Packaged in protective sleeves.",
        "Smudge-proof for kids."
      ]
    },
    {
      id: 51,
      "name": "Graphite Portrait Sketch",
      "price": 999,
      "originalPrice": 2499,
      "location": "Vadodara",
      "description": "Design art for learning toys or games.",
      "image": "../images/Grapencil3.jpg",
      "size": "86 cm x 48 cm",
      "dimensions": "86L x 48W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Circular",
      "theme": "Portraits",
      "uses": "Playroom, Classroom, Home",
      "frameType": "Framed",
      "wallArtForm": "Graphite",
      "material": "Paper",
      "about": [
        "Fine graphite for detail.",
        "Educational paper quality.",
        "Great for toy designs.",
        "Packaged in protective sleeves.",
        "Smudge-proof for kids."
      ]
    },
    {
      id: 52,
      "name": "Graphite City Sketch",
      "price": 999,
      "originalPrice": 2499,
      "location": "Bhubaneswar",
      "description": "Create art focused on ecology and conservation.",
      "image": "../images/Grapencil5.jpg",
      "size": "86 cm x 48 cm",
      "dimensions": "86L x 48W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Circular",
      "theme": "Cityscape",
      "uses": "Eco Center, Home, Office",
      "frameType": "Framed",
      "wallArtForm": "Graphite",
      "material": "Paper",
      "about": [
        "Eco-friendly graphite art.",
        "High-quality paper for detail.",
        "Ideal for conservation.",
        "Packaged in protective sleeves.",
        "Smudge-proof for display."
      ]
    },
    {
      id: 53,
      "name": "Graphite Abstract Sketch",
      "price": 999,
      "originalPrice": 2499,
      "location": "Bhubaneswar",
      "description": "Craft wearable art pieces.",
      "image": "../images/Grapencil6.jpg",
      "size": "86 cm x 48 cm",
      "dimensions": "86L x 48W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Circular",
      "theme": "Abstract",
      "uses": "Fashion Show, Home, Studio",
      "frameType": "Unframed",
      "wallArtForm": "Graphite",
      "material": "Fabric",
      "about": [
        "Wearable graphite designs.",
        "Fabric for comfort.",
        "Great for fashion art.",
        "Packaged in protective bags.",
        "Washable for use."
      ]
    },
    {
      id: 54,
      "name": "Graphite Portrait Art",
      "price": 999,
      "originalPrice": 2499,
      "location": "Bhubaneswar",
      "description": "Create murals or wall art for interior design projects.",
      "image": "../images/Grapencil7.jpg",
      "size": "86 cm x 48 cm",
      "dimensions": "86L x 48W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Circular",
      "theme": "Portraits",
      "uses": "Home, Office, Interior",
      "frameType": "Framed",
      "wallArtForm": "Graphite",
      "material": "Paper",
      "about": [
        "Interior graphite portraits.",
        "Durable paper for walls.",
        "Perfect for design projects.",
        "Packaged in protective sleeves.",
        "Smudge-proof for display."
      ]
    },
    {
      id: 55,
      "name": "Graphite Abstract Form",
      "price": 999,
      "originalPrice": 2499,
      "location": "Srinagar",
      "description": "Create custom art pieces as unique gifts.",
      "image": "../images/Grapencil8.jpg",
      "size": "86 cm x 48 cm",
      "dimensions": "86L x 48W cm",
      "items": 3,
      "orientation": "Portrait",
      "shape": "Circular",
      "theme": "Abstract",
      "uses": "Gift Shop, Home, Studio",
      "frameType": "Framed",
      "wallArtForm": "Graphite",
      "material": "Paper",
      "about": [
        "Unique graphite gift art.",
        "Durable paper for gifting.",
        "Perfect for special occasions.",
        "Packaged in elegant boxes.",
        "Smudge-proof for display."
      ]
    },
    {
      id: 56,
      "name": "Graphite Wildlife Sketch",
      "price": 999,
      "originalPrice": 2499,
      "location": "Bhubaneswar",
      "description": "Provide visual representations for literature or textbooks.",
      "image": "../images/Grapencil9.jpg",
      "size": "86 cm x 48 cm",
      "dimensions": "86L x 48W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Circular",
      "theme": "Wildlife",
      "uses": "Library, Classroom, Home",
      "frameType": "Framed",
      "wallArtForm": "Graphite",
      "material": "Paper",
      "about": [
        "Literary graphite wildlife.",
        "Durable paper for books.",
        "Perfect for textbooks.",
        "Packaged in protective sleeves.",
        "Smudge-proof for display."
      ]
    },
    {
      id: 57,
      "name": "Graphite Cityscape Art",
      "price": 999,
      "originalPrice": 2499,
      "location": "Bhubaneswar",
      "description": "Create motivational art to encourage or uplift viewers.",
      "image": "../images/Grapencil10.jpg",
      "size": "86 cm x 48 cm",
      "dimensions": "86L x 48W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Circular",
      "theme": "Cityscape",
      "uses": "Office, Gym, Home",
      "frameType": "Framed",
      "wallArtForm": "Graphite",
      "material": "Paper",
      "about": [
        "Motivational city graphite.",
        "Durable paper for inspiration.",
        "Perfect for office decor.",
        "Packaged in protective sleeves.",
        "Smudge-proof for display."
      ]
    },
    {
      id: 58,
      name: "Abstract Art Painting",
      price: 1199,
      originalPrice: 2999,
      location: "Mumbai",
      description: "Craft wearable art pieces.",
      image: "../images/Grapencil11.jpg",
      size: "89 cm x 51 cm",
      dimensions: "89L x 51W cm",
      items: 3,
      orientation: "Portrait",
      shape: "Rectangular",
      theme: "Madhubani",
      uses: "Living room, Bedroom, Office, Hotel, Dining room, Bathroom, Bar",
      frameType: "Framed",
      wallArtForm: "Painting",
      material: "Cardboard",
      about: [
        "Premium Sparkle lamination for a luxurious look.",
        "High-gloss mirror effect for stunning wall decor.",
        "Perfect for living rooms, bedrooms, and offices.",
        "Safely packaged in a rigid hard-board box.",
        "Water-resistant surface ensures long-lasting decor.",]
    },
    {
      id: 59,
      name: "Abstract Art Painting",
      price: 1199,
      originalPrice: 2999,
      location: "Mumbai",
      description: "Use art to visualize scientific concepts or data.",
      image: "../images/Grapencil12.jpg",
      size: "89 cm x 51 cm",
      dimensions: "89L x 51W cm",
      items: 3,
      orientation: "Portrait",
      shape: "Rectangular",
      theme: "Madhubani",
      uses: "Living room, Bedroom, Office, Hotel, Dining room, Bathroom, Bar",
      frameType: "Framed",
      wallArtForm: "Painting",
      material: "Cardboard",
      about: [
        "Premium Sparkle lamination for a luxurious look.",
        "High-gloss mirror effect for stunning wall decor.",
        "Perfect for living rooms, bedrooms, and offices.",
        "Safely packaged in a rigid hard-board box.",
        "Water-resistant surface ensures long-lasting decor.",]
    },
    {
      id: 60,
      name: "Abstract Art Painting",
      price: 1199,
      originalPrice: 2999,
      location: "Mumbai",
      description: "Design art for products like t-shirts, mugs, or posters.",
      image: "../images/brushes14.jpg",
      size: "89 cm x 51 cm",
      dimensions: "89L x 51W cm",
      items: 3,
      orientation: "Portrait",
      shape: "Rectangular",
      theme: "Madhubani",
      uses: "Living room, Bedroom, Office, Hotel, Dining room, Bathroom, Bar",
      frameType: "Framed",
      wallArtForm: "Painting",
      material: "Cardboard",
      about: [
        "Premium Sparkle lamination for a luxurious look.",
        "High-gloss mirror effect for stunning wall decor.",
        "Perfect for living rooms, bedrooms, and offices.",
        "Safely packaged in a rigid hard-board box.",
        "Water-resistant surface ensures long-lasting decor.",]
    },
    {
      id: 61,
      "name": "Watercolor Madhubani Art",
      "price": 1299,
      "originalPrice": 3099,
      "location": "Delhi",
      "description": "Use art in educational tools like flashcards or worksheets.",
      "image": "../images/brushes2.png",
      "size": "90 cm x 52 cm",
      "dimensions": "90L x 52W cm",
      "items": 2,
      "orientation": "Landscape",
      "shape": "Square",
      "theme": "Madhubani",
      "uses": "Classroom, Study, Home",
      "frameType": "Unframed",
      "wallArtForm": "Watercolor",
      "material": "Paper",
      "about": [
        "Vivid watercolor hues for educational appeal.",
        "Eco-friendly materials for sustainable learning.",
        "Ideal for classroom and home use.",
        "Packaged in recyclable tubes.",
        "Fade-resistant for lasting quality."
      ]
    },
    {
      id: 62,
      "name": "Sketched Madhubani Design",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Kolkata",
      "description": "Sell art pieces or auction them for charitable causes.",
      "image": "../images/brushes3.jpg",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Madhubani",
      "uses": "Gallery, Charity Event, Home",
      "frameType": "Framed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Hand-drawn details for a unique appeal.",
        "Archival quality for auction preservation.",
        "Perfect for charity displays.",
        "Shipped in protective wooden crates.",
        "Customizable for special causes."
      ]
    },
    {
      id: 63,
      "name": "Golden Madhubani Painting",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Chennai",
      "description": "Organize art projects that involve community participation.",
      "image": "../images/brushes4.jpg",
      "size": "92 cm x 54 cm",
      "dimensions": "92L x 54W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Madhubani",
      "uses": "Community Center, Park, Home",
      "frameType": "Framed",
      "wallArtForm": "Painting",
      "material": "Wood",
      "about": [
        "Metallic gold finish for community pride.",
        "Durable wood frame for stability.",
        "Great for collaborative spaces.",
        "Packaged with reinforced corners.",
        "Resistant to wear for public use."
      ]
    },
    {
      id: 64,
      "name": "Watercolor Madhubani Scene",
      "price": 1199,
      "originalPrice": 2999,
      "location": "Bangalore",
      "description": "Use art to educate about different periods and styles.",
      "image": "../images/brushes5.jpg",
      "size": "88 cm x 50 cm",
      "dimensions": "88L x 50W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Circular",
      "theme": "Madhubani",
      "uses": "Museum, School, Home",
      "frameType": "Unframed",
      "wallArtForm": "Watercolor",
      "material": "Paper",
      "about": [
        "Delicate watercolor tones for history lessons.",
        "Lightweight for easy display.",
        "Ideal for educational decor.",
        "Packaged in elegant gift boxes.",
        "Waterproof coating for durability."
      ]
    },
    {
      id: 65,
      "name": "Charcoal Madhubani Sketch",
      "price": 999,
      "originalPrice": 2499,
      "location": "Hyderabad",
      "description": "Develop art that highlights local landmarks or culture.",
      "image": "../images/brushes6.jpg",
      "size": "87 cm x 49 cm",
      "dimensions": "87L x 49W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Madhubani",
      "uses": "Cultural Center, Home, Gallery",
      "frameType": "Framed",
      "wallArtForm": "Charcoal",
      "material": "Paper",
      "about": [
        "Bold charcoal lines for cultural depth.",
        "Acid-free paper for longevity.",
        "Perfect for landmark decor.",
        "Shipped with protective sleeves.",
        "Easy to clean surface."
      ]
    },
    {
      id: 66,
      "name": "Oil Madhubani Art",
      "price": 1499,
      "originalPrice": 3499,
      "location": "Pune",
      "description": "Create murals or wall art for interior design projects.",
      "image": "../images/brushes7.jpg",
      "size": "91 cm x 53 cm",
      "dimensions": "91L x 53W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Square",
      "theme": "Madhubani",
      "uses": "Home, Office, Interior",
      "frameType": "Unframed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Rich oil colors for interior elegance.",
        "Canvas material for a textured look.",
        "Great for design projects.",
        "Packaged in sturdy cardboard tubes.",
        "UV-resistant for color preservation."
      ]
    },
    {
      id: 67,
      "name": "Watercolor Madhubani Nature",
      "price": 1299,
      "originalPrice": 3099,
      "location": "Jaipur",
      "description": "Use art in spas, yoga studios, or meditation rooms.",
      "image": "../images/brushes8.jpg",
      "size": "89 cm x 51 cm",
      "dimensions": "89L x 51W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Madhubani",
      "uses": "Spa, Yoga Studio, Home",
      "frameType": "Framed",
      "wallArtForm": "Watercolor",
      "material": "Paper",
      "about": [
        "Soft watercolor tones for relaxation.",
        "Handmade paper for authenticity.",
        "Ideal for meditation spaces.",
        "Packaged with eco-friendly wraps.",
        "Moisture-resistant for longevity."
      ]
    },
    {
      id: 68,
      "name": "Graphite Madhubani Drawing",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Ahmedabad",
      "description": "Use abstract art to represent ideas or emotions.",
      "image": "../images/brushes9.jpg",
      "size": "86 cm x 48 cm",
      "dimensions": "86L x 48W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Madhubani",
      "uses": "Studio, Home, Gallery",
      "frameType": "Framed",
      "wallArtForm": "Graphite",
      "material": "Paper",
      "about": [
        "Detailed graphite shading for emotion.",
        "High-quality paper for fine lines.",
        "Perfect for abstract expression.",
        "Shipped in protective portfolios.",
        "Smudge-proof coating applied."
      ]
    },
    {
      id: 69,
      "name": "Oil Madhubani Abstract",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Surat",
      "description": "Produce wildlife or landscape art to showcase natural beauty.",
      "image": "../images/brushes10.jpg",
      "size": "90 cm x 52 cm",
      "dimensions": "90L x 52W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Madhubani",
      "uses": "Nature Center, Home, Office",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Rich oil colors for natural beauty.",
        "Canvas stretched for durability.",
        "Enhances nature displays.",
        "Packaged in reinforced crates.",
        "Oil-resistant finish for protection."
      ]
    },
    {
      id: 70,
      "name": "Sketched Madhubani Form",
      "price": 1199,
      "originalPrice": 2999,
      "location": "Lucknow",
      "description": "Create custom art pieces as unique gifts.",
      "image": "../images/brushes11.jpg",
      "size": "88 cm x 50 cm",
      "dimensions": "88L x 50W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Circular",
      "theme": "Madhubani",
      "uses": "Gift Shop, Home, Studio",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Minimalist sketch for unique gifts.",
        "Lightweight paper for versatility.",
        "Great for special occasions.",
        "Packaged in recyclable boxes.",
        "Fade-resistant for long use."
      ]
    },
    {
      id: 71,
      "name": "Watercolor Madhubani City",
      "price": 1299,
      "originalPrice": 3099,
      "location": "Nagpur",
      "description": "Create patterns or prints for clothing and accessories.",
      "image": "../images/brushes13.jpg",
      "size": "87 cm x 49 cm",
      "dimensions": "87L x 49W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Madhubani",
      "uses": "Fashion Studio, Home, Boutique",
      "frameType": "Framed",
      "wallArtForm": "Watercolor",
      "material": "Fabric",
      "about": [
        "Vivid city watercolor for fashion.",
        "Fabric for performance use.",
        "Perfect for clothing design.",
        "Shipped in protective bags.",
        "Washable for durability."
      ]
    },
    {
      id: 72,
      "name": "Charcoal Madhubani Nature",
      "price": 999,
      "originalPrice": 2499,
      "location": "Indore",
      "description": "Make art that serves a purpose, like decorative furniture.",
      "image": "../images/watercolor1.jpg",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Madhubani",
      "uses": "Furniture Store, Home, Office",
      "frameType": "Framed",
      "wallArtForm": "Charcoal",
      "material": "Wood",
      "about": [
        "Functional charcoal nature art.",
        "Wood for furniture design.",
        "Great for decor pieces.",
        "Shipped in protective crates.",
        "Smudge-proof for use."
      ]
    },
    {
      id: 73,
      "name": "Oil Madhubani Landscape",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Bhopal",
      "description": "Integrate art into building designs or public installations.",
      "image": "../images/watercolor2.jpg",
      "size": "91 cm x 53 cm",
      "dimensions": "91L x 53W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Square",
      "theme": "Madhubani",
      "uses": "Public Building, Home, Park",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Architectural oil landscape art.",
        "Canvas for a bold look.",
        "Ideal for public spaces.",
        "Packaged in reinforced crates.",
        "UV-protected for longevity."
      ]
    },
    {
      id: 74,
      "name": "Sketched Madhubani Abstract",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Patna",
      "description": "Provide visual representations for literature or textbooks.",
      "image": "../images/watercolor3.jpg",
      "size": "86 cm x 48 cm",
      "dimensions": "86L x 48W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Madhubani",
      "uses": "Library, Classroom, Home",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Literary sketched abstracts.",
        "Light paper for books.",
        "Perfect for textbooks.",
        "Packaged in protective covers.",
        "Fade-resistant for display."
      ]
    },
    {
      id: 75,
      "name": "Watercolor Madhubani Wildlife",
      "price": 1299,
      "originalPrice": 3099,
      "location": "Kanpur",
      "description": "Design art pieces as mementos for tourists or events.",
      "image": "../images/watercolor4.jpg",
      "size": "89 cm x 51 cm",
      "dimensions": "89L x 51W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Circular",
      "theme": "Madhubani",
      "uses": "Tourist Shop, Event Space, Home",
      "frameType": "Framed",
      "wallArtForm": "Watercolor",
      "material": "Paper",
      "about": [
        "Memento wildlife watercolors.",
        "High-quality paper for vibrancy.",
        "Ideal for tourist gifts.",
        "Shipped in reinforced tubes.",
        "Water-resistant for longevity."
      ]
    },
    {
      id: 76,
      "name": "Charcoal Madhubani City",
      "price": 999,
      "originalPrice": 2499,
      "location": "Visakhapatnam",
      "description": "Develop logos, packaging, or branding materials for companies.",
      "image": "../images/watercolor5.jpg",
      "size": "87 cm x 49 cm",
      "dimensions": "87L x 49W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Madhubani",
      "uses": "Corporate Office, Home, Shop",
      "frameType": "Framed",
      "wallArtForm": "Charcoal",
      "material": "Paper",
      "about": [
        "Branding charcoal city art.",
        "Acid-free paper for preservation.",
        "Perfect for company decor.",
        "Packaged with protective sleeves.",
        "Smudge-proof coating."
      ]
    },
    {
      id: 77,
      "name": "Oil Madhubani Portrait",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Coimbatore",
      "description": "Use art to raise awareness for social issues or campaigns.",
      "image": "../images/watercolor6.jpg",
      "size": "90 cm x 52 cm",
      "dimensions": "90L x 52W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Square",
      "theme": "Madhubani",
      "uses": "Community Center, Home, Office",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Social issue oil portraits.",
        "Canvas for a rich texture.",
        "Ideal for campaign decor.",
        "Shipped in wooden crates.",
        "UV-protected for longevity."
      ]
    },
    {
      id: 78,
      "name": "Sketched Madhubani Nature",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Madurai",
      "description": "Design art for festivals, holidays, or special occasions.",
      "image": "../images/watercolor13.jpg",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Madhubani",
      "uses": "Festival Ground, Home, Event Space",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Festive nature sketches.",
        "Light paper for ease.",
        "Great for holiday decor.",
        "Packaged in sturdy tubes.",
        "Fade-resistant for use."
      ]
    },
    {
      id: 79,
      "name": "Watercolor Madhubani Abstract",
      "price": 1299,
      "originalPrice": 3099,
      "location": "Thiruvananthapuram",
      "description": "Create memorial art to honor individuals or events.",
      "image": "../images/watercolor8.jpg",
      "size": "88 cm x 50 cm",
      "dimensions": "88L x 50W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Madhubani",
      "uses": "Memorial Site, Home, Gallery",
      "frameType": "Framed",
      "wallArtForm": "Watercolor",
      "material": "Paper",
      "about": [
        "Memorial abstract watercolors.",
        "High-quality paper for vibrancy.",
        "Ideal for honoring events.",
        "Shipped in reinforced tubes.",
        "Waterproof for durability."
      ]
    },
    {
      id: 80,
      "name": "Graphite Madhubani Portrait",
      "price": 999,
      "originalPrice": 2499,
      "location": "Vadodara",
      "description": "Produce art for entertainment purposes, such as movie posters or game designs.",
      "image": "../images/watercolor9.jpg",
      "size": "86 cm x 48 cm",
      "dimensions": "86L x 48W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Circular",
      "theme": "Madhubani",
      "uses": "Movie Set, Game Studio, Home",
      "frameType": "Framed",
      "wallArtForm": "Graphite",
      "material": "Paper",
      "about": [
        "Entertaining graphite portraits.",
        "Durable paper for posters.",
        "Great for game designs.",
        "Packaged in protective sleeves.",
        "Smudge-proof for display."
      ]
    },
    {
      id: 81,
      "name": "Oil Madhubani City",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Agra",
      "description": "Use art therapy to aid in mental health and emotional well-being.",
      "image": "../images/watercolor10.jpg",
      "size": "91 cm x 53 cm",
      "dimensions": "91L x 53W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Madhubani",
      "uses": "Therapy Room, Home, Clinic",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Therapeutic oil city scenes.",
        "Canvas for a serene look.",
        "Ideal for mental health.",
        "Shipped in wooden crates.",
        "UV-protected for longevity."
      ]
    },
    {
      id: 82,
      "name": "Sketched Madhubani Wildlife",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Varanasi",
      "description": "Create motivational art to encourage or uplift viewers.",
      "image": "../images/watercolor11.jpg",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Madhubani",
      "uses": "Office, Gym, Home",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Motivational wildlife sketches.",
        "Light paper for ease.",
        "Great for inspiration.",
        "Packaged in sturdy tubes.",
        "Fade-resistant for use."
      ]
    },
    {
      id: 83,
      "name": "Watercolor Madhubani Portrait",
      "price": 1299,
      "originalPrice": 3099,
      "location": "Allahabad",
      "description": "Design promotional materials like posters or banners for businesses.",
      "image": "../images/watercolor12.jpg",
      "size": "89 cm x 51 cm",
      "dimensions": "89L x 51W cm",
      "items": 2,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Madhubani",
      "uses": "Business Office, Home, Shop",
      "frameType": "Framed",
      "wallArtForm": "Watercolor",
      "material": "Paper",
      "about": [
        "Promotional portrait watercolors.",
        "High-quality paper for clarity.",
        "Ideal for business decor.",
        "Shipped in reinforced tubes.",
        "Waterproof for durability."
      ]
    },
    {
      id: 84,
      "name": "Charcoal Madhubani Abstract",
      "price": 999,
      "originalPrice": 2499,
      "location": "Amritsar",
      "description": "Use art to teach concepts, history, or skills in educational settings.",
      "image": "../images/charcoal1.jpg",
      "size": "87 cm x 49 cm",
      "dimensions": "87L x 49W cm",
      "items": 3,
      "orientation": "Portrait",
      "shape": "Square",
      "theme": "Madhubani",
      "uses": "Classroom, School, Home",
      "frameType": "Framed",
      "wallArtForm": "Charcoal",
      "material": "Paper",
      "about": [
        "Educational charcoal abstracts.",
        "Acid-free paper for longevity.",
        "Perfect for teaching.",
        "Packaged with protective sleeves.",
        "Smudge-proof coating."
      ]
    },
    {
      id: 85,
      "name": "Oil Madhubani Nature",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Jodhpur",
      "description": "Document historical events or cultural practices through art.",
      "image": "../images/charcoal2.jpg",
      "size": "90 cm x 52 cm",
      "dimensions": "90L x 52W cm",
      "items": 2,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Madhubani",
      "uses": "Museum, Home, Gallery",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      "about": [
        "Historical oil nature scenes.",
        "Canvas for a rich texture.",
        "Ideal for museum decor.",
        "Shipped in wooden crates.",
        "UV-protected for longevity."
      ]
    },
    {
      id: 86,
      "name": "Sketched Madhubani City",
      "price": 1099,
      "originalPrice": 2799,
      "location": "Udaipur",
      "description": "Illustrate narratives through visual art forms like paintings or comics.",
      "image": "../images/charcoal3.jpg",
      "size": "85 cm x 50 cm",
      "dimensions": "85L x 50W cm",
      "items": 4,
      "orientation": "Portrait",
      "shape": "Oval",
      "theme": "Madhubani",
      "uses": "Comic Studio, Home, Library",
      "frameType": "Unframed",
      "wallArtForm": "Sketch",
      "material": "Paper",
      "about": [
        "Narrative city sketches.",
        "Light paper for comics.",
        "Great for storytelling.",
        "Packaged in sturdy tubes.",
        "Fade-resistant for use."
      ]
    },
    {
      id: 87,
      "name": "Watercolor Madhubani Landscape",
      "price": 1299,
      "originalPrice": 3099,
      "location": "Rajkot",
      "description": "Use art to express emotions through drawings or sculptures.",
      "image": "../images/charcoal4.png",
      "size": "88 cm x 50 cm",
      "dimensions": "88L x 50W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Madhubani",
      "uses": "Studio, Home, Gallery",
      "frameType": "Framed",
      "wallArtForm": "Watercolor",
      "material": "Paper",
      "about": [
        "Emotional landscape watercolors.",
        "High-quality paper for vibrancy.",
        "Ideal for expression.",
        "Shipped in reinforced tubes.",
        "Waterproof for durability."
      ]
    },
    {
      id: 88,
      name: "Graphite Madhubani Wildlife",
      "price": 999,
      "originalPrice": 2499,
      "location": "Nashik",
      "description": "Create vibrant paintings to decorate a living room wall.",
      "image": "../images/charcoal5.jpg",
      "size": "86 cm x 48 cm",
      "dimensions": "86L x 48W cm",
      "items": 2,
      "orientation": "Portrait",
      "shape": "Circular",
      "theme": "Madhubani",
      "uses": "Living Room, Home, Office",
      "frameType": "Framed",
      "wallArtForm": "Graphite",
      "material": "Paper",
      "about": [
        "Vibrant wildlife graphite art.",
        "Durable paper for walls.",
        "Perfect for living rooms.",
        "Packaged in protective sleeves.",
        "Smudge-proof for display."
      ]
    },
    {
      id: 89,
      "name": "Oil Madhubani Abstract",
      "price": 1399,
      "originalPrice": 3299,
      "location": "Aurangabad",
      "description": "Create vibrant paintings to decorate a living room wall.",
      "image": "../images/charcoal6.jpg",
      "size": "91 cm x 53 cm",
      "dimensions": "91L x 53W cm",
      "items": 3,
      "orientation": "Landscape",
      "shape": "Rectangular",
      "theme": "Madhubani",
      "uses": "Living Room, Home, Office",
      "frameType": "Framed",
      "wallArtForm": "Oil",
      "material": "Canvas",
      about: [
        "Vibrant oil abstract designs.",
        "Canvas for a rich texture.",
        "Perfect for living room decor.",
        "Shipped in wooden crates.",
        "UV-protected for longevity."
      ]
    },



    // Add more products here
  ]);
  const addToCart = (product) => {
    if (itemCount >= MAX_ITEMS) {
      alert(`Maximum limit of ${MAX_ITEMS} items reached!`);
      return;
    }
    const existingItem = cartItems.find((item) => item.id === product.id);
    if (existingItem) {
      setCartItems(
        cartItems.map((item) =>
          item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item
        )
      );
    } else {
      setCartItems([...cartItems, { ...product, quantity: 1 }]);
    }
    setTotalPrice(totalPrice + product.price);
    setItemCount(itemCount + 1);
  };

  const cartLength = cartItems.reduce((total, item) => total + item.quantity, 0);

  return (
    <Router>
      <CustomNavbar cartLength={cartLength} />
      <CategoryNavbar />
      <Routes>
        <Route
          path="/"
          element={
            <>
              <BannerCarousel />
              <HomePage />
            </>
          }
        />
        <Route
          path="/painting"
          element={<PaintingPage products={products.filter((p) => p.category === "painting")} />}
        />
        <Route
          path="/sketches"
          element={<SketchesPage products={products.filter((p) => p.category === "sketches")} />}
        />
        <Route
          path="/sketchbook"
          element={<SketchbookPage products={products.filter((p) => p.category === "sketchbook")} />}
        />
        <Route
          path="/graphitepencil"
          element={
            <GraphitePencilPage products={products.filter((p) => p.category === "graphitepencil")} />
          }
        />
        <Route
          path="/brushes"
          element={<BrushesPage products={products.filter((p) => p.category === "brushes")} />}
        />
        <Route
          path="/watercolor"
          element={<WatercolorPage products={products.filter((p) => p.category === "watercolor")} />}
        />
        <Route
          path="/charcoals"
          element={<CharcoalsPage products={products.filter((p) => p.category === "charcoals")} />}
        />
        <Route path="/cart" element={<Cart products={products} addToCart={addToCart} />} />
        <Route path="/search" element={<SearchResults products={products} addToCart={addToCart} />} />
        <Route path="/sell" element={<SellProduct />} />
        <Route path="/product/:id" element={<ProductDetails products={products} addToCart={addToCart} />} />
      </Routes>
      <Footer />
    </Router>
  );
}

export default App;
